#!/bin/bash
# =============================================================================
# regenerate_CPP_FFS1.sh
#
# Performs a full cleanup and regeneration of CPP_FFS1 HDDM files:
#   1. Reduces total_events/total_jobs by 10x in all rbhg_config.json files
#   2. Removes vectors_*.hddm files ONLY (NOT .txt files - those are kept forever)
#   3. Removes merged .hddm files from vectors/ (non-vectors_*.hddm files)
#   4. Removes MCWrapper/ directories (will be regenerated by prepareSimulation)
#   5. Regenerates only the first N hddm files from existing .txt files (no lead)
#   6. Re-runs prepareSimulation.py for all 4 datasets
#
# NOTE: .txt files are NEVER deleted. They represent precious compute that will
#       be used for full runs in the future. Only HDDM files are regenerated.
#
# Usage:
#   bash regenerate_CPP_FFS1.sh           # Full run
#   bash regenerate_CPP_FFS1.sh --dry-run # Preview only, no changes
#
# =============================================================================

set -u

FRAMEWORK="/work/halld/home/acschick/channels/swif2-generator-framework"
OUTPUT_BASE="$FRAMEWORK/output/RBHG/CPP_FFS1"
HDDM_SCRIPTS="$FRAMEWORK/hddm_scripts"
DRY_RUN=false
STEP4_ONLY=false

for arg in "${@}"; do
    case "$arg" in
        --dry-run)    DRY_RUN=true ;;
        --step4-only) STEP4_ONLY=true ;;
    esac
done

if $DRY_RUN; then
    echo "============================================================"
    echo "  DRY RUN MODE - No files will be deleted or modified"
    echo "============================================================"
fi

# --step4-only: jump directly to prepareSimulation (skip Steps 1-3)
if $STEP4_ONLY; then
    echo "============================================================"
    echo "  --step4-only: Skipping directly to prepareSimulation.py"
    echo "============================================================"
fi

if ! $STEP4_ONLY; then

echo ""
echo "============================================================"
echo "  CPP_FFS1 Regeneration Script"
echo "  - 10x event reduction (use fewer files, keep all txt)"
echo "  - Remove HDDM files only (regenerate without lead recoil)"
echo "  - Remove MCWrapper dirs (regenerate fresh)"
echo "  - .txt files are NEVER touched"
echo "============================================================"
echo ""

# ------------------------------------------------------------
# Helper: run or print command depending on dry-run mode
# ------------------------------------------------------------
run_cmd() {
    if $DRY_RUN; then
        echo "    [DRY RUN] $*"
    else
        eval "$*"
    fi
}

# ------------------------------------------------------------
# STEP 1: Update rbhg_config.json files (10x event reduction)
# ------------------------------------------------------------
echo "============================================================"
echo "STEP 1: Updating event counts in rbhg_config.json files"
echo "============================================================"
echo ""

if $DRY_RUN; then
    python3 "$FRAMEWORK/hddm_scripts/reduce_events_10x.py" --dry-run
else
    python3 "$FRAMEWORK/hddm_scripts/reduce_events_10x.py"
fi

if [ $? -ne 0 ]; then
    echo "ERROR: reduce_events_10x.py failed. Aborting."
    exit 1
fi

echo ""

# ------------------------------------------------------------
# Dataset definitions: dataset -> new_total_jobs
# BC/SIM: 400M / 10 = 40M events, 8000/10 = 800 jobs
# qDATAq: 40M  / 10 = 4M  events, 800/10  = 80 jobs
# Also: run_number for ascii2hddm (characteristic run per polarization)
# ------------------------------------------------------------
# Format: "dataset/simdir|new_jobs|run_number"
DATASET_LIST=(
    "BC_FF1/2205_135DEG_FF1_IRADOFF|800|101582"
    "BC_FF1/2205_45DEG_FF1_IRADOFF|800|101586"
    "BC_FF1/2205_AMO_FF1_IRADOFF|800|101615"
    "BC_FFN/2205_135DEG_FFN_IRADOFF|800|101582"
    "BC_FFN/2205_45DEG_FFN_IRADOFF|800|101586"
    "BC_FFN/2205_AMO_FFN_IRADOFF|800|101615"
    "SIM_FF1/2205_135DEG_FF1_IRADOFF|800|101582"
    "SIM_FF1/2205_45DEG_FF1_IRADOFF|800|101586"
    "SIM_FF1/2205_AMO_FF1_IRADOFF|800|101615"
    "qDATAq_FFN/2205_135DEG_FFN_IRADOFF|80|101582"
    "qDATAq_FFN/2205_45DEG_FFN_IRADOFF|80|101586"
    "qDATAq_FFN/2205_AMO_FFN_IRADOFF|80|101615"
)

# ------------------------------------------------------------
# STEP 2: Remove HDDM files and MCWrapper directories
#         (.txt files are NEVER touched)
# ------------------------------------------------------------
echo "============================================================"
echo "STEP 2: Removing HDDM files and MCWrapper/ directories"
echo "        (NO .txt files will be deleted)"
echo "============================================================"
echo ""

for entry in "${DATASET_LIST[@]}"; do
    IFS='|' read -r rel_path new_jobs run_number <<< "$entry"
    dir="$OUTPUT_BASE/$rel_path"
    vectors_dir="$dir/vectors"
    mcwrapper_dir="$dir/MCWrapper"

    echo "--- $rel_path ---"

    if [ ! -d "$dir" ]; then
        echo "  WARNING: Directory not found: $dir"
        echo ""
        continue
    fi

    # Count files (never touching .txt)
    n_hddm_indiv=$(find "$vectors_dir" -name 'vectors_*.hddm' 2>/dev/null | wc -l)
    n_hddm_merged=$(find "$vectors_dir" -name '*.hddm' ! -name 'vectors_*.hddm' 2>/dev/null | wc -l)
    n_txt=$(find "$vectors_dir" -name 'vectors_*.txt' 2>/dev/null | wc -l)
    echo "  .txt files (KEEPING ALL): $n_txt"
    echo "  vectors_*.hddm to remove: $n_hddm_indiv"
    echo "  merged *.hddm to remove:  $n_hddm_merged"

    # 2a. Remove individual vectors_*.hddm files (will regenerate only first N)
    if [ "$n_hddm_indiv" -gt 0 ]; then
        echo "  Removing vectors_*.hddm files..."
        run_cmd "find '$vectors_dir' -name 'vectors_*.hddm' -delete"
    fi

    # 2b. Remove merged hddm file(s) (non vectors_*.hddm)
    if [ "$n_hddm_merged" -gt 0 ]; then
        echo "  Removing merged *.hddm file(s)..."
        run_cmd "find '$vectors_dir' -name '*.hddm' ! -name 'vectors_*.hddm' -delete"
    fi

    # 2c. Remove MCWrapper directory
    if [ -d "$mcwrapper_dir" ]; then
        echo "  Removing MCWrapper/ directory..."
        run_cmd "rm -rf '$mcwrapper_dir'"
    else
        echo "  MCWrapper/ not found (already clean)"
    fi

    echo ""
done

# ------------------------------------------------------------
# STEP 3: Submit swif2 jobs to convert txt → HDDM in parallel
#         20 files per job → ~40 total jobs per dataset
#         Uses ascii2hddm.py with pb208 target (no lead by default)
# ------------------------------------------------------------
echo "============================================================"
echo "STEP 3: Submitting swif2 jobs for parallel txt → HDDM conversion"
echo "        (pb208 target = no lead recoil by default)"
echo "        Each job converts 20 files; ~744 jobs total"
echo "============================================================"
echo ""

SUBMIT_SCRIPT="$FRAMEWORK/hddm_scripts/submit_hddm_regen_swif2.py"

if [ ! -f "$SUBMIT_SCRIPT" ]; then
    echo "ERROR: submission script not found: $SUBMIT_SCRIPT"
    exit 1
fi

if $DRY_RUN; then
    echo "  [DRY RUN] python3 $SUBMIT_SCRIPT --dry-run --force --files-per-job 20"
    echo "  (Note: in real mode, Step 2 will have cleared all existing HDDM files"
    echo "   so all files will be queued - not just the ones shown in dry-run below)"
    echo ""
    python3 "$SUBMIT_SCRIPT" --dry-run --force --files-per-job 20
else
    python3 "$SUBMIT_SCRIPT" --force --files-per-job 20
    if [ $? -ne 0 ]; then
        echo "ERROR: swif2 job submission failed."
        exit 1
    fi

    # Extract workflow name from submission output (last line matching the pattern)
    WORKFLOW_NAME=$(python3 "$SUBMIT_SCRIPT" --dry-run --files-per-job 20 2>/dev/null | grep "Workflow:" | head -1 | awk '{print $2}')

    echo ""
    echo "============================================================"
    echo "  swif2 jobs have been ADDED to the workflow."
    echo "  To START running them, execute:"
    echo ""
    echo "    swif2 run -workflow <workflow_name>"
    echo ""
    echo "  To check status:"
    echo "    swif2 status -workflow <workflow_name>"
    echo "    swif2 status -workflow <workflow_name> -jobs"
    echo ""
    echo "  Step 4 (prepareSimulation) MUST wait until the workflow"
    echo "  completes.  Run it manually when all jobs are done:"
    echo ""
    echo "    bash $FRAMEWORK/regenerate_CPP_FFS1.sh --step4-only"
    echo "============================================================"
    echo ""
    echo "  Exiting now - STEP 4 will run after swif2 jobs complete."
    exit 0
fi

fi  # end: if ! $STEP4_ONLY

# ------------------------------------------------------------
# STEP 4: Re-run prepareSimulation.py for all datasets
# ------------------------------------------------------------
echo "============================================================"
echo "STEP 4: Re-running prepareSimulation.py for all datasets"
echo "============================================================"
echo ""

cd "$FRAMEWORK" || exit 1

DATASETS=("BC_FF1" "BC_FFN" "SIM_FF1" "qDATAq_FFN")
FAILED=()

for dataset in "${DATASETS[@]}"; do
    config="output/RBHG/CPP_FFS1/$dataset/run_period_master_config.json"

    if [ ! -f "$config" ]; then
        echo "WARNING: Config not found: $config - skipping"
        continue
    fi

    echo "--- Running prepareSimulation.py for $dataset ---"
    echo "  Config: $config"

    if $DRY_RUN; then
        echo "  [DRY RUN] python3 prepareSimulation.py $config --no-merge-prompt"
        echo ""
    else
        echo "  Running..."
        python3 prepareSimulation.py "$config" --no-merge-prompt

        if [ $? -eq 0 ]; then
            echo "  ✓ $dataset completed successfully"
        else
            echo "  ✗ $dataset FAILED"
            FAILED+=("$dataset")
        fi
        echo ""
    fi
done

# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------
echo "============================================================"
echo "SUMMARY"
echo "============================================================"

if $DRY_RUN; then
    echo ""
    echo "DRY RUN complete. Re-run without --dry-run to apply changes."
else
    echo ""
    echo "Completed datasets:  $((${#DATASETS[@]} - ${#FAILED[@]})) / ${#DATASETS[@]}"

    if [ ${#FAILED[@]} -gt 0 ]; then
        echo ""
        echo "FAILED datasets:"
        for f in "${FAILED[@]}"; do
            echo "  ✗ $f"
        done
        echo ""
        echo "To retry a failed dataset manually:"
        echo "  cd $FRAMEWORK"
        echo "  python3 prepareSimulation.py output/RBHG/CPP_FFS1/<DATASET>/run_period_master_config.json --no-merge-prompt"
        exit 1
    else
        echo ""
        echo "✓ All datasets processed successfully"
        echo ""
        echo "New event counts:"
        echo "  BC_FF1, BC_FFN, SIM_FF1: 400M → 40M events (800 jobs × 50k events)"
        echo "  qDATAq_FFN:               40M →  4M events  (80 jobs × 50k events)"
        echo ""
        echo "HDDM files regenerated WITHOUT Pb208 lead recoil (ascii2hddm pb208 default)"
        echo "All original .txt generator files preserved"
    fi
fi
