#!/bin/bash
# MCWrapper submission script
# Generated by prepareSimulation.py
#
# NOTE: This script uses the minimal working command format for containerized MCWrapper.
# The full pipeline (geant, mcsmear, recon) will run by default with batch=2.
# To customize pipeline steps or clean flags, you must manually edit MC.config or this script.

# Set container bind paths for 2018 (1801/1808) containerized runs
export APPTAINER_BIND="/work/halld,/work/osgpool,/volatile/halld/,$PWD,/cvmfs/singularity.opensciencegrid.org/"

$MCWRAPPER_CENTRAL/gluex_MC.py RBHGPATHTOMCCONFIG RBHGRUNRANGE RBHGNEVENTS per_file=RBHGPERFILE batch=RBHGBATCHMODE shell=bash logdir=RBHGLOGDIR
